// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobileDev = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:ee221f47-9850-492b-9505-5adc04dd3aed",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_JRIWfBn5v",
    "aws_user_pools_web_client_id": "2nkno0atmk03jsi9s23tg5r2tp",
    "mandatorySignIn": false,
};

const awsmobileProd = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:5bb0adcf-9dad-4cc2-90ac-c2c588f4616a",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_1FCb5c5UK",
    "aws_user_pools_web_client_id": "2l4qvphjfm3tf7nsp9ghjou6rt",
    "mandatorySignIn": false,
};


export default awsmobileProd;
